AppBundle\Entity\Contacts:
    type: entity
    table: contacts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fullname:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        message:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        regDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: reg_date
    lifecycleCallbacks: {  }
