AppBundle\Entity\Informations:
    type: entity
    table: informations
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        age:
            type: integer
            nullable: false
            options:
                unsigned: false
        profil:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        presentation:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
