AppBundle\Entity\Socialnetworks:
    type: entity
    table: socialnetworks
    indexes:
        informations_id:
            columns:
                - informations_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        link:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        informations:
            targetEntity: Informations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                informations_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
