AppBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        regDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: reg_date
    lifecycleCallbacks: {  }
